### ISSUE TITLE
Not compatible with the new Google Calendar

### ISSUE THREAD

**Issue by mortpett** [TheHackmeister/TodoistGoogleCalendar#1]
Are you planning on making this brilliant addon compatible with the new Google Calendar?

**Comment by TheHackmeister** [comment]
You know, I didn't actually know anyone used it. If you're using it (or were using it), I'll shoot to make it compatible, but I don't see myself snagging the time to do it until the holidays.

**Comment by mortpett** [comment]
That would be awesome, but take your time :-)

**Comment by gbombara** [comment]
I also second this. I use your extension every day and love it.
Thank you very much!

**Comment by TheHackmeister** [comment]
I've updated the extension to be compatible with the new Google Calendar. It'll take a dayish to go through chrome's review process. Let me know if you have any problems with it!
